version: "3"

services:
    app:
      container_name: dantownms-app
      image: php:7.3.29
      command: ["sh", "-c", "php artisan serve --host=0.0.0.0 --port=4000"]
      ports:
        - "4000:4000"
      working_dir: /app
      volumes:
        - ./:/app
